version: 2.0
jobs:
  test-without-redis:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: install ts-node
          command: npm install typescript ts-node
      - run:
          name: test
          command: node_modules/.bin/ts-node example/index.ts
  test-with-redis:
    docker:
      - image: circleci/node:10
      - image: redis
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: npm install
          command: npm install
      - run:
          name: install ts-node
          command: npm install typescript ts-node
      - run:
          name: test
          command: node_modules/.bin/ts-node example/index.ts
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-without-redis
      - test-with-redis